README.md

Also fixes the format of the README to comply with markdown linter rules.
Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>
closes #48 
closes #49

fix links in the Table of Contents

---

101-bundle-json.md

Correct invalid JSON in examples

---

101-bundle-json.md
102-invocation-image.md
103-bundle-runtime.md

This brings 2 changes:
- Bundle.json `images` field is now a map (`component logical name` -> `image definition`)
- `images` map is injected at runtime so that the invocation image can use it when declarative substitutions are not applicable
Relates to discussion in #58

Introduce image map injection

---

104-claims.md

This seems to be the defacto format used in JSON.
Closes #63

fix: specify ISO-8601 Extended Format for timestamps

---

100-CNAB.md
901-process.md

* Link to the definition of WD from the spec
* Remove text saying that we use semver
* Explain that the version is a _target_ that is applied before we hit it

Clarify use of semver

---

101-bundle-json.md
schema/bundle.schema.json

Custom actions lacked a description field. This fixed that. Also introduces stateless custom actions to implement things like `dry-run`, `help` etc.
The docker-app tool currently abuse the spec to do this kind of things: `inspect` and `render` actions are executed without passing credentials, and are used to visualize the effect of parameter values on the generated stack. We think it should be part of the standard as we see similar requirements for many other generic CNAB (Helm, Terraform, ...)

Add description and stateless fields to action

---

101-bundle-json.md

This adds the `license` field and marks which metadata fields are optional.
Closes #96
Closes #94

fix: Clean up description of metadata

---

101-bundle-json.md
schema/bundle.schema.json

With the multiplication of CNAB runtime implementations, it may occur some custom action clash as multiple runtimes will define different actions using the same name (eg `status`).
I guess it is not be a problem for read-only (`"modifies": false`) actions, but for the others the semantic may change dramatically depending the runtime.
To tackle this problem I suggest we add the following line to the spec:
```
The action name SHOULD be namespaced by the CNAB implementation which generated the bundle.
```
so runtimes will be able to resolve correctly their own custom actions (or if they decide to support custom actions from other runtimes).

Introduce namespaced custom actions

---

Dockerfile.ajv
Makefile
brigade.js
validate.sh

Implements https://github.com/deislabs/cnab-spec/issues/109
Adds:
- `validate.sh`, a schema validation script for vetting all bundle.json examples in `examples` against the schema files in `schema`
- `Makefile` with validation targets invoking said script, where 
- `make validate` defaults to a Docker-based validation approach
- `make validate-local` runs locally
- (open to switching these such that `validate` runs locally and `validate-docker` runs in the Docker image, if desired)
- `brigade.js` for running this validation on pull request and `master` branch push events

feat(ci): add validation automation

---

101-bundle-json.md
103-bundle-runtime.md
104-claims.md

This removes the autogeneration of CNAB_P_* environment variables, and requires the `destination` field on parameters.
Additionally, this change provides a little more clarification on how `path` is to be handled in `destination`.
Closes #105

fix: remove CNAB_P_* support

---

101-bundle-json.md
schema/bundle.schema.json

This switches the validator keywords to a subset of the ones used in JSONSchema.
Closes #54
Closes #55

fix: switch to JSON Schema for parameter validation.

---

validate.sh

I just added a small doc string at the top of the validate script so that others would know how to run it.

fix: add inline doc string on validate.sh

---

101-bundle-json.md
901-process.md
examples/101.01-bundle.json
schema/bundle.schema.json

This PR supersedes #28 
This adds a `custom` key as a designated place where extensions may be inserted into the `bundle.json` file.
See #28 for relevant discussion.

Bundle extension fields through `custom`

---

000-index.md
100-CNAB.md
103-bundle-runtime.md
400-claims.md
README.md
examples/400.01-claim.json
schema/claim.schema.json
validate.sh

This removes 104 and adds 400, with largely the same content. A few clarifications were made along the way in order to move all mention of claims from CNAB Core. Schema and example have been added.
Closes #84

docs: Move claims to separate specification

---

101-bundle-json.md
schema/bundle.schema.json

This adds an optional "apply-to" field to parameters definition to make
a parameter usable only for a specific set of actions.
eg.: we could have a `follow` parameter that could only apply to the
`logs` custom action of a CNAB (as it only makes sense in the context of
this action)

Intoduce action-specific parameters

---

000-index.md
104-bundle-formats.md
README.md

This defines the thick and thin bundles in terms of representation of the format. It defines the thick bundle file system layout, as well.

feat: define bundle formats

---

101-bundle-json.md
schema/bundle.schema.json

Some CNABs might have a need for parameters taking binary data as values. An exemple of such a CNAB would be a generic Helm Chart deployer declaring a HelmChart parameter that should be an actual Tarball with the whole chart in it.
This PR adds support for this scenario and specify what defaultValue / allowedValues should look like for parameters of type `bytes`.

Add support for `bytes` parameter type

---

schema/bundle.schema.json

There were two description fields in the parameter definition. Only one is defined in the spec, so I removed the other.

fix: remove redundant field in JSON schema

---

examples/805.01-status.json
schema/status.schema.json
validate.sh

This changes the status schema to work with the schema validators that we use. It's now less efficient, but it passes JSONSchema Validator and `ajv` now.
Closes #120

fix: Update schema for status messages

---

101-bundle-json.md
103-bundle-runtime.md
examples/101.01-bundle.json
examples/103.1-bundle.json
schema/bundle.schema.json

This removes the `refs` section from the specification, and intentionally backs out the definition of how invocation images are to perform substitutions of image names. This decision was arrived at on issue #117 after trying a few other ways of handling this behavior.
Supersedes #117
Closes #113

fix: remove `refs` from specification

---

000-index.md
100-CNAB.md
101-bundle-json.md
102-invocation-image.md
103-bundle-runtime.md
104-bundle-formats.md
200-CNAB-registries.md
300-CNAB-security.md
400-claims.md
801-declarative-images.md
802-credential-sets.md
803-base-bundles.md
804-repositories.md
805-well-known-custom-actions.md
901-process.md

This PR adds a small bit of metadata to each page, in order to structure the markdown content for rendering as a website:
The site is a [work in progress](https://github.com/deislabs/cnab.io/pull/10) - [github.com/deislabs/cnab.io/pull/10](https://github.com/deislabs/cnab.io/pull/10)
It will fetch the contents of this repo and import it into cnab.io - rather than adding Hugo _config/theme/noise_ to this repo.

add front matter for rendering a hugo website 

---

brigade.js

The public Kashti instance that displays recent Brigade CI builds for many projects, including this one, has changed.  It now lives at: https://brigadecore.github.io/kashti

chore(brigade.js): update kashti build url

---

README.md

Fixes broken links in Table of Contents section of README.md. Links are broken due to case sensitive URLs/File Names. 
closes #151

Fixed broken links in Table of Contents (case sensitive)

---

schema/bundle.schema.json

The "required" field only applies to "object" types and so should be
defined within the schema for a maintainer item, not the whole "maintainers" list.

Moves schema required field to correct location

---

101-bundle-json.md
103-bundle-runtime.md
104-bundle-formats.md
400-claims.md
examples/101.01-bundle.json
examples/101.02-bundle.json
examples/103.1-bundle.json
schema/bundle.schema.json

As requested during the March 27 community meeting, here is a new PR that outlines the proposal to change the `parameters` section to extend JSON Schema. The primary driver behind this PR is to provide more complex configuration inputs like arrays and object with significantly improved validation of those inputs. Additionally, this change serves to reduce confusion between the "JSON Schema"-alike `parameters` section of the current spec and JSON Schema.
This PR still leaves unresolved the concern of the representation of these complex parameter types inside the invocation image. If we support complex configuration then we will need the spec to make a determination on the format of that data when it is placed at a `destination`.
/cc @youreddy

Converts parameters section to extend JSON Schema

---

101-bundle-json.md
103-bundle-runtime.md
examples/103.1-bundle.json
schema/bundle.schema.json

Provide a normative way of specifying the original image name so that
invocation images can map the original to the new image name.
Also tidy up the definition of the image field by using the recommended CAS
SHA form in examples and by deleting the misleading `REGISTRY/NAME:TAG`
syntax.
Fixes https://github.com/deislabs/cnab-spec/issues/134

Include original image names in image map

---

802-credential-sets.md
803-repositories.md
README.md

Base bundles were removed from the spec in PR https://github.com/deislabs/cnab-spec/pull/154.
This PR cleans links to the removed spec

Remove links to base bundles

---

101-bundle-json.md

We missed the `writeOnly` field when we first landed JSONSchema support in parameters. This PR remedies that.
cc @youreddy

Adds missing writeOnly parameter definition

---

governance.md

Because this is the first governance change, I'll ask that we get an lgtm from each core maintainer on this PR. After this PR, only a super-majority will be required to make governance changes just like all other decisions for this repo.

add more info on governance

---

901-process.md

The earlier draft of section 900 was provisional. We now have a designated workflow for proceeding through the standardization process, so this replaces the provisional model.

Switch the draft development process from the W3 model to the JDF model

---

101-bundle-json.md
schema/bundle.schema.json

This adds a `required` property under `credentials`, and declares that all credentials are optional unless `required` is set to true.
Closes #119.

add 'required' keyword for credentials

---

101-bundle-json.md
102-invocation-image.md
103-bundle-runtime.md

This changes the language in several places. Instead of suggesting the _driver_ determines which invocation image is run, it now reads as the _CNAB runtime_ must select the driver.
Further, I added a clarification that if no sufficient image is found, the runtime must return an error.
Closes #180

remove mention of drivers, which are specific to duffle

---

000-index.md
805-airgap.md

Initial draft for 805-airgap
Goal was to make explicit assumptions and requirements for the airgap/disconnected scenarios that have been previously been discussed across issues and meetings as well as limit the complexity introduced to support these
Related to 
#147 
#142

805-airgap section

---

101-bundle-json.md
schema/bundle.schema.json

* Adds specification to the output section that outputs must be under /cnab/app/outputs
* Adds specification to params/creds that they must NOT be under /cnab/app/outputs
cc: @jlegrone
Closes #184

Added some wording to the specification regarding output paths

---

104-bundle-formats.md

Fixes https://github.com/deislabs/cnab-spec/issues/182
Fixes https://github.com/deislabs/cnab-spec/issues/171

Thick bundles no longer store images in multiple TAR files

---

101-bundle-json.md
103-bundle-runtime.md
examples/101.01-bundle.json
examples/101.02-bundle.json
examples/103.1-bundle.json
schema/bundle.schema.json

- these schema are now defined by name in a top-level field called
"definitions"
- parameters will define the schema for their field by referencing the
name of a definition in their own "definition" field
This did not touch the `outputs` section, but it would make sense to also factor the validation for those fields out to this same top-level `definitions` field. That would separate the concerns of validation from those of naming and exposing those user inputs during invocation.

Factors JSONSchema definitions out of parameters

---

101-bundle-json.md

This cleans up the text in the credentials section as highlighted by #198 and makes it similar to what we have defined for parameters.

Cleanup text in credentials section

---

101-bundle-json.md
examples/101.01-bundle.json
examples/101.02-bundle.json
schema/bundle.schema.json

This PR includes changes to push outputs into a sub-object called `fields` and to introduce a new `required` array at that same level. Doing so brings outputs fully inline with the current experience for `parameters`.
Resolves https://github.com/deislabs/cnab-spec/issues/197

Factors JSONSchema fields out of outputs

---

100-CNAB.md
101-bundle-json.md
102-invocation-image.md
103-bundle-runtime.md

- Addresses issue #144
- Related issue #195 
- This PR mounts the bundle file to`/cnab/bundle.json`. I didn't feel a strong need to throw it into a subdirectory inside of `cnab` but I'm happy to update the PR if people would rather have the bundle definition at a different location.
- I didn't update the [image map section](https://github.com/deislabs/cnab-spec/blob/master/103-bundle-runtime.md#image-maps) in this PR. I figured we could to do that once #195 gets resolved. 
/cc @glyn @radu-matei

Add bundle.json file to invocation image

---

OWNERS

Some of my priorities have changed and I haven't been as involved lately. I'd love to propose @jeremyrickard as core maintainer on the spec as a replacement for me. He has already been doing great work across the spec, porter and duffle and should have actually been on the core maintainer list when I originally committed it.

add Jeremy as core maintainer

---

102-invocation-image.md

As mentioned in #201, the references in the 102 document to bundle.json are confusing because the invocation image should not be built with bundle.json file in it. This PR removes those confusing references.
cc @ryanmoran

Remove references to bundle.json from 102-invocation-image

---

101-bundle-json.md
102-invocation-image.md
103-bundle-runtime.md
400-claims.md
500-CNAB-dependencies.md
802-credential-sets.md
804-well-known-custom-actions.md
CONTRIBUTING.md
examples/103.1-bundle.json
examples/400.01-claim.json
examples/805.01-status.json
schema/bundle.schema.json
schema/claim.schema.json
schema/status.schema.json

Now that much of the large changes in 1.0 have landed, I went through and fixed a number of formatting and whitespace issues. The changes are to the formatting of JSON documents and the removal of extraneous whitespace. In the process, I discovered and resolved a few cases where we were showing examples of JSON snippets that were not valid JSON (extra trailing commas or missing closing brackets).

Formatting and whitespace corrections

---

101-bundle-json.md
103-bundle-runtime.md
examples/101.02-bundle.json
schema/bundle.schema.json

This PR adds an immutable flag to the parameter definition in `101-bundle-json.md` and adds wording to `103-bundle-runtime.md` to indicate that if an immutable parameter value is given at any time other than runtime, it should result in an error. 
Closes #181

Add immutable flag to parameters.

---

101-bundle-json.md
examples/101.03-bundle.json
schema/bundle.schema.json

This PR introduces a `requiredExtensions` object and modifies
the wording of 101-bundle-json.md to refine the existing custom
extensions section. Relevant example and JSON schema changes included.

Adding "requiredExtensions" to core spec

---

400-claims.md
schema/claim.schema.json

This PR adds outputs to the claim spec to allow adding outputs to Duffle.
https://github.com/deislabs/duffle/issues/747
cc @ryanmoran @jeremyrickard @carolynvs @simonferquel

Add outputs to claim spec

---

100-CNAB.md
101-bundle-json.md
104-bundle-formats.md
805-airgap.md

- Usage of the terms thick and thin have been standardized
- "we" has been removed, replaced with passive voice
- Other small grammatical fixes have been made
Closes #210

fix: terminology and grammar

---

500-CNAB-dependencies.md
examples/500.01-dependencies.json
schema/dependencies.schema.json
validate.sh

* When I went to [add support for dependencies in cnab-go](https://github.com/deislabs/cnab-go/pull/55), I realized that the example json wasn't using array/object properly. This is what I get for writing json embedded in markdown... 🤦‍♀️
* Use bool instead of bool string for prereleases
**Update:** Since this isn't part of the core spec, it can't live at the root because that messes up the json schema valiation. So it will live under the custom extensions, custom.
* Add a json schema document
* Add a validation test for the schema doc

Fix dependency example json

---

101-bundle-json.md
103-bundle-runtime.md
examples/101.01-bundle.json
examples/101.02-bundle.json
examples/101.03-bundle.json
schema/bundle.schema.json

- a75deff34324bceb3883a1373f6e148df1d93167 Autoformats json with prettier (this was pretty helpful for fixing indentation everywhere)
- f599dcb00350238012ac721b9d02c8e3d42f5e40 Removes the `fields` and `required` properties from `parameters` in favor of `required` property directly on the parameter type.
Closes #222

Make "required" a property of parameter

---

200-CNAB-registries.md

Adds a registry icon, which is a variant of the main CNAB logo.

add a CNAB Registry icon

---

300-CNAB-security.md

Adds a security icon, which is a variant of the main CNAB logo.

add a CNAB Security icon

---

101-bundle-json.md
103-bundle-runtime.md
examples/101.02-bundle.json
schema/bundle.schema.json

This removes the `immutable` attribute from parameters per Issue #229
Closes #229

Remove the `immutable` attribute from parameters

---

schema/claim.schema.json

Fixes misspelling of the `underway` status on the claim spec

fix(claim.schema.json): s/underay/underway

---

schema/claim.schema.json

Fixes misspelling of the `description` field under `status`.

fix(claim.schema.json): s/descripton/description

---

README.md

At the August 7th Community Meeting, it was proposed that we put a freeze on the specification so that duffle could catch up on implementing the core concepts in 1.0.
This PR serves as a vote to start the freeze and include a description of it in the readme. 
@radu-matei @simonferquel @technosophos @jeremyrickard

Vote: Specification Freeze

---

101-bundle-json.md
schema/bundle.schema.json
schema/definitions.schema.json
validate.sh

I originally tried to just reference the pieces of JSON schema we wanted, replacing things but since there are internal references inside of the json schema itself, it seemed cleaner to make a standalone schema, called `definitions.schema.json` and reference that. 
Summary:
* All the fields that were `number` before are integer
* Removed `number` as a type, only integer
* Updated the validation.sh script to reference the new file 
Fixes #256

Update definitions schema to use a bespoke JSON Schema Version

---

101-bundle-json.md

This makes clear the initial intent for invocation image matching: The first invocation image to match the pattern is the _only_ image which should be executed.
Closes #244 

clarify what to do when multiple invocation images match a pattern

---

400-claims.md

This is a further clarification to #248 re: claims, but answers the question more broadly. It explains the way claims should store parameters while not storing credentials. And it explains why this is the case.
This is not a blocker to CNAB Core 1.0

explain how claims treat parameters and credentials differently, and why

---

103-bundle-runtime.md

Fixes: https://github.com/deislabs/cnab-spec/issues/237
This is quite verbose but I tried to capture all the concerns in the issue and give bundle authors guidelines for what to do.

Clarify failed action handling

---

100-CNAB.md
901-process.md
README.md

This commit indicates that the CNAB specification is now a published final version.
This requires unanimous approval from the executive directors. The following people MUST mark this LGTM:
@chris-crone 
@technosophos
When this PR is merged, the tag `cnab-core-1.0` should be created in Git. 
As with any other PR, all are welcomed to review this PR for grammar, wording, spelling, and technical correctness.

Final Approval for CNAB Core 1.0 Specification

---

101-bundle-json.md
400-claims.md
examples/101.01-bundle.json
examples/101.02-bundle.json
examples/101.03-bundle.json
examples/400.01-claim.json

As part of the Core 1.0 release, we did not bump the bundle schemaVersion from v1.0.0-WD to v1.0.0.
cc @rumpl who caught this.

Bump bundle schemaVersion to v1.0.0

---

804-well-known-custom-actions.md

As per https://github.com/deislabs/cnab-go/pull/154/files#r340791888, it seems like there should be no need for a separate `io.cnab.status+json` action when `io.cnab.status` also exists given that `io.cnab.status` could define a cnab output for the `status.json` file.

Make status.json a CNAB Output

---

400-claims.md

I feel like this particular section really adds no useful content to the spec. It's overly general. I think it's left over from my first draft of the spec before I split claims out into its own section.

fix: remove an unnecessary section

---

400-claims.md

This defines an optional bundle reference as described in #297. I am not sure whether we should also have a relocation map stored inside of the claim, but if so this should be a separate PR.
Closes #297

add bundleReference to the claim specification

---

400-claims.md

This adds two related features:
- `$CNAB_CLAIMS_VERSION` specifies (within the CNAB invocation image) what version of the claims specification is supported
- `/cnab/claim.json` is the required path in the invocation image where the claim must be presented.

add CNAB_CLAIMS_VERSION and mount path for claim.json

---

103-bundle-runtime.md

In the `bundle.json` section, the `destination` of `parameters` may point to `env` or `path`. I'm guessing this text was left from an earlier version of the spec.

Indicate that both parameters and credentials may inject files.

---

CONTRIBUTING.md

This replaces the CLA requirement text with an explanation of the DCO.
Closes #306

Add text explaining the DCO requirement.

---

OWNERS

As per our discussion during the January 8th meeting ([notes and recording here](https://hackmd.io/s/SyGcBcwQ4#)), this PR adds @silvin-lubecki as core maintainer for the CNAB specification.

Add Silvin as core maintainer

---

802-credential-sets.md

Since credential sets could be stored in different locations, not just the file system, having timestamps inside the credential set helps users remember when they last worked with the item. Currently tools such as duffle or porter have to rely on the file timestamps which isn't feasible once we start storing the credential sets in databases, etc.
See corresponding PR in cnab-go https://github.com/cnabio/cnab-go/pull/173

Add timestamps to credential set spec

---

400-claims.md

This fixes issues with the CNAB Claims spec.
This PR removes any mention of `release` (which was confusing), and defines the terms `installation` and `revision`. The text is fixed to make usages consistent.
Closes #298 

Clarify terminolgy for installation and revision

---

103-bundle-runtime.md

This addresses the root problems in #316, which were about encoding the data inside of env vars. Somehow, we gave the false impression that the body of an env var had to be JSON. I have backed out the text that seemed to imply that.
Note that I have gone with fairly minimal restraints (adopting Chris's SHOULD instead of a MUST) because we need to facilitate some interesting edge cases where a runtime needs to support uncommon character encodings or payload types.
Keep in mind that the author of the bundle.js is presumed to be an expert in the invocation image. So protecting the bundle author from the invocation image (and vice versa) is not a high priority. So this focuses mainly on the relationship between the runtime and the bundle. For a runtime that is tooled to support rare/bespoke …

replaced ambiguous description of environment variable content

---

400-claims.md
schema/claim.schema.json

This changes the `name` field on a claim to be `installation`
BREAKING CHANGE: This will require updates to both the Rust and Go CNAB libraries
Depends upon #309 
Closes #303

Change 'name' to 'installation' on Claim

---

schema/bundle.schema.json

Removes the `pattern` property from the definitions for parameters and credentials.
The negative lookup regex used proved problematic for validation (namely, incompatible with golang implementations, of which cnab's most-used - https://github.com/cnabio/cnab-go - is one).
This change would therefore mean implementations are responsible for enforcing spec expectations as regards these path strings, namely, `"Specified path MUST NOT be a subpath of /cnab/app/outputs."` as seen in https://github.com/cnabio/cnab-spec/blob/master/101-bundle-json.md.
Potential solution to https://github.com/cnabio/cnab-spec/issues/215
Corresponding cnab-go implementation: https://github.com/cnabio/cnab-go/pull/180

ref(bundle.schema.json): remove pattern property from param/cred path

---

examples/400.01-claim.json
schema/claim.schema.json

* Updates the `required` section of the `claim` schema to require `installation` instead of `name` (see https://github.com/cnabio/cnab-spec/pull/310 for genesis of this change)
* Updates example

fix(claim.schema.json): s/name/installation in required section

---

101-bundle-json.md
schema/bundle.schema.json

Adds a `display` field for custom actions so that a human friendly name can be shown for each custom action.
Closes #242 

add 'title' field for custom actions

---

400-claims.md
schema/claim.schema.json

This PR changes "underway" to "pending". Since this changes the behavior of cnab-go and libcnab-rs, we need to create issues in those repos if we decide to merge this.
See #309 (comment) for discussion of what the name of this field should be.
Supersedes #325 

change 'underway' to 'pending' in the claims spec

---

400-claims.md
schema/claim.schema.json

The current definition for the pending (previously underway) status is difficult to understand when it is acceptable to use and what it really means about the state of the installation. It's described as both a long term state and temporary. It is also described as "to be avoided".
We would like to redefine the state to make it more clear on what the state means, and to make it acceptable for tools to use. Pending now means that the operation has been requested (most likely queued) but has not begun executing. Tools that are immediately executing commands as
they are issued would most likely choose to not use this state. However solutions that accept bundle operations from many users at once, for example a cnab operator, may choose to use this state.
This also introduces a new state: …

Clarify pending status, introduce running

---

Makefile
brigade.js

* Splits the two validation targets apart
* Maintains running example validation all the time (PRs, master, etc.)
* Only runs URL validation on master push events (new schemas won't be hosted by cnab.io until they exist on master and hence validation must wait)

ref(ci): split validation targets apart

---

901-process.md

Much of the CNAB versioning regime was "tribal knowledge" or explained tersely in the governance documents. This codifies the versioning scheme.
Closes #342 

painstakingly explained versioning

---

Makefile
README.md
brigade.js
brigade.json

* adds CI for publishing schema on git tag pushes
* adds entry on where to find published schema in README
* refactors brigade.js with latest brigade-utils helpers
Contributes towards https://github.com/cnabio/cnab-spec/issues/346
Depends on https://github.com/cnabio/cnab.io/pull/32 (merged)
TODO (after approval):

feat(ci): publish versioned schema

---

100-CNAB.md

The 100 section apparently still had two references to a signed bundle being `bundle.cnab`.
This PR _just_ removes those two references, but I suspect we could also add a note in the _History_ section describing the changes.
The main question is whether this can be considered an errata change (see #351).
This PR is opened against the 1.0.1 branch - is this the right approach?
How should `master` be updated?
cc @chris-crone @technosophos

Remove outdated reference to `bundle.cnab`

---

OWNERS

I'd like to nominate @jlegrone as a maintainer of the specification. He has made several contributions to the spec (in the form of PRs, issues, and discussion) and he regularly attends the community meetings.

Add jlegrone as a maintainer

---

901-process.md

* Adds clarification around updates to the non-normative section
(I believe I've captured what was discussed in today's CNAB Community Meeting)

docs(901-process.md): clarify non-normative protocol

---

OWNERS

According to the [CNAB general meeting notes from April 29th](https://hackmd.io/TfLYtyRnS8Kfx4ekgLwWLg?both#April-29th---General-Meeting), and as voted by a supermajority of the spec maintainers, this PR adds @carolynvs as a spec maintainer.

Add Carolyn Van Slyck (@carolynvs) as spec maintainer

---

OWNERS

@chris-crone pointed out that when we added Silvin as a spec maintainer (#315), we were also supposed to remove Simon from the OWNERS file, since he started working on another project. 
This PR updates the OWNERS file accordingly.

Remove Simon from the OWNERS file

---

901-process.md
README.md

* add CNAB Security 1.0.0 listing to `Branch-Tag Structure` section of README
* add note around this convention in the Process doc

docs(*): branch tag structure

---

000-index.md
200-CNAB-registries.md
201-representing-CNAB-in-OCI.md
210-on-disk-representation.md
807-registries-known-implementations.md

This is based on the work @chris-crone, @silvin-lubecki, and I have done in [this HackMD document](https://hackmd.io/@ccrone/HySy-hQEI).
There are still sections that we need to add, but hopefully this gives everyone in the community better visibility in the process.

Add initial draft for registry specification

---

101-bundle-json.md

* Clarifies which type of digest must be used for the contentDigest field of an invocation or bundle image
Proposed fix for https://github.com/cnabio/cnab-spec/issues/287

docs(101-bundle-json.md): add clarification around contentDigest value

---

000-index.md
100-CNAB.md
101-bundle-json.md
README.md

Docs and other updates in anticipation of the forthcoming/proposed cnab-core-1.1.0 release.
The main spec change prompting this minor release is the following clarification: https://github.com/cnabio/cnab-spec/issues/287
Ref https://github.com/cnabio/cnab-spec/issues/387

Updates in anticipation of cnab-core-1.1.0

---

103-bundle-runtime.md
400-claims.md
schema/claim-result.schema.json

Whilst re-reviewing the current state of the Claims Spec doc, I found some areas that appear to need updating.
Also, added the missing `custom` field to the claim result schema.
This is in anticipation of finalizing the Claims Spec for its 1.0.0 release.

feat(claims): update claims spec and result schema

---

README.md

* Adds a link to the README for the recent [CNAB Claims 1.0.0](https://github.com/cnabio/cnab-spec/tree/cnab-claims-1.0.0) release

chore(README.md): add CNAB Claims 1.0.0 link

---

Dockerfile.ajv
Makefile

* Pins the ajv cli that we use to validate json to a known working version
It looks like the latest release(s) introduce new flags/usage that we'll need to look into when/if we bump.  (See https://github.com/cnabio/cnab-spec/issues/397)

chore(*): pin ajv cli to known working version

---

101-bundle-json.md
500-CNAB-dependencies.md
810-well-known-custom-extensions.md

* The dependendencies custom extension was sometimes specified with its full key `io.cnab.dependencies` and in other places used its shorthand `dependencies`. I've updated the spec to be clear that the key to use is the full `io.cnab.dependencies`.
* Remove outdated info on Porter's dep resolution
Fixes #403

Clarify dependencies custom extension key 

---

101-bundle-json.md
examples/101.02-bundle.json
schema/bundle.schema.json

Allow restricting a credential to a list of actions, just like Parameters can do today. This allows a credential to not have to be
passed in for actions that do not use it. 
Closes #366

Add applyTo to Credentials

---

schema/definitions.schema.json

I didn't realize that the URLs embedded in our schema are redirects to the **latest** code on main. I should not have removed
definitions.schema.json from the repository when we no longer used it.

Add back definitions.schema.json
