cnabio/cnab-spec

README.md
=> Add Communications section to README

101-bundle-json.md, 105-signing.md
closes #89
Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>
=> rename uri to image

101-bundle-json.md, 104-claims.md, 105-signing.md
Closes #45 
This is a rebasing of #46. Something about the cnab-spec going from private -> public after I made the original PR broke the link for me to easily update the PR.
=> Introducing namespacing to the names

101-bundle-json.md, 104-claims.md, 105-signing.md, examples/101.01-bundle.json, examples/101.02-bundle.json
=> Require Canonical JSON for bundle.json

101-bundle-json.md, 103-bundle-runtime.md, examples/103.1-bundle.json, schema/bundle.schema.json
=> Address various ambiguities in spec and schema

101-bundle-json.md
This addresses a comment: https://github.com/deislabs/cnab-spec/issues/39#issuecomment-462941465
Related to #39
=> fix: Explain the difference between credentials and parameters

104-claims.md, 105-signing.md, schema/bundle.schema.json
When #62 got merged, we forgot to update the schema.
=> fix: update schema for images

101-bundle-json.md, 103-bundle-runtime.md, examples/101.01-bundle.json, examples/101.02-bundle.json, examples/103.1-bundle.json
Updates example bundle.json files in `examples` to specify the required parameter destination where applicable.
=> fix(examples): update examples with required parameter destination

000-index.md, 100-CNAB.md, 105-signing.md, 200-CNAB-registries.md, 300-CNAB-security.md, 804-repositories.md, README.md
Also add placeholder for CNAB Registries spec.
This PR also removes the older OpenPGP-based signing mechanism.
=> feat: add CNAB security spec (rough draft)

101-bundle-json.md
+ link to bundle formats section
=> clarify thin and thick bundle mention

104-bundle-formats.md
Fixes https://github.com/deislabs/cnab-spec/issues/129
=> Encourage thick bundle layer deduplication

CONTRIBUTING.md, OWNERS, governance.md
+ update CONTRIBUTING.md
resolves #141
=> add governance doc, OWNERS file

101-bundle-json.md, schema/bundle.schema.json
Fixes https://github.com/deislabs/cnab-spec/issues/157
=> Support relocation of invocation images

OWNERS
I'm pleased to announce that @youreddy is now a core maintainer on the CNAB spec. 🎉
=> add Urvashi as core maintainer

500-CNAB-dependencies.md, README.md
This is the first step towards #156. I decided to submit a proposal for specifying named dependencies as a first step, instead of jumping directly to what I proposed in the comments of that issue. I explain a bit more in the Q&A (see md file). Hopefully this is merged and then we can move onto that! 😇 
It's also related to #65 which honestly is a HUGE issue and this only covers a tiny bit.
cc @ryanmoran
=> Dependencies Spec: Named Dependencies

101-bundle-json.md, schema/bundle.schema.json
To match casing elsewhere, rename apply-to to applyTo.
Closes #149
=> change apply-to to applyTo

schema/bundle.schema.json
=> fixed the schema version description in the JSON schema file

101-bundle-json.md, 103-bundle-runtime.md, examples/101.01-bundle.json, examples/101.02-bundle.json, schema/bundle.schema.json
Fixes: #187
This PR introduces a "fields" property to the parameters definition. Where things were previously defined under "parameters", and parallel to the "required" property, they now live under "fields".
=> Update the structure of "parameters" to introduce a "fields" property

100-CNAB.md, README.md
Re-reading parts of the spec resulted in a few little nits.
=> Various minor fixes

brigade.js
* add issue comment event handler so that test suites can be (re-)run via `/brig run`
=> ci(brigade.js): add issue comment handling

000-index.md
Some links were broken and returned a 404 error
=> Fix broken links in 000-index.md

101-bundle-json.md, 103-bundle-runtime.md, 805-airgap.md, examples/103.1-bundle.json, examples/103.2-relocation-mapping.json, schema/bundle.schema.json, schema/relocation-mapping.schema.json, validate.sh
Fixes https://github.com/deislabs/cnab-spec/issues/195
=> Introduce relocation mapping

101-bundle-json.md
Fixes https://github.com/deislabs/cnab-spec/issues/209, plus a little rewording of neighboring paragraphs.
cc @technosophos
=> Update wording around unicode character classes

103-bundle-runtime.md
=> Changed MUST to SHOULD in an exampe to reach parity with the descriptive text

100-CNAB.md
=> Link to Canonical JSON

101-bundle-json.md
Signed-off-by: Trishank K Kuppusamy <trishank.kuppusamy@datadoghq.com>
=> Clarify why bundle.json is mounted in the invocation image

101-bundle-json.md, 400-claims.md, examples/101.01-bundle.json, examples/101.02-bundle.json, examples/101.03-bundle.json, schema/bundle.schema.json
close #234 
`cnab-go` PR - https://github.com/deislabs/cnab-go/pull/85
=> Remove fields from outputs

400-claims.md, examples/400.01-claim.json
Closes https://github.com/deislabs/cnab-spec/issues/240
=> fix(400-claims.md): add mention of the custom field in a claim

104-bundle-formats.md
Changed `move` to `have`.
Closes #258 
=> fix: corrected a typo

101-bundle-json.md
=> clearify wording on writeOnly

101-bundle-json.md
=> fix: clarify the wording on stateless actions

101-bundle-json.md
Resolves issue https://github.com/deislabs/cnab-spec/issues/247
=> Add clarification to `readOnly` definition

103-bundle-runtime.md
=> Clarify parameters are encoded as json strings

101-bundle-json.md, 103-bundle-runtime.md
=> Clarify defaults for outputs and parameters

103-bundle-runtime.md
=> Removed extra were

103-bundle-runtime.md
Fixes: https://github.com/deislabs/cnab-spec/issues/246
I wanted to get this up quickly for review. I'm not particularly happy with the phrase "bundle version" so if anyone has a better suggestion please do comment that here!
=> Clarify upgrade version handling responsibility

README.md
This commit marks the Working Group Acceptance (GA) of the CNAB Core 1.0 specification.
=> CNAB Core 1.0 GA

README.md
The JDF has provided us a mailing list via groups.io. I've added that to the README.md
=> Add mailing list

400-claims.md
This is the beginning of work to get the claims spec ready to publish.
=> 400 Claims: Define host environment

804-well-known-custom-actions.md
It turns out the flow when you hit the "e" button on github to propose an edit never produces a DCO, so you need to sync the repo locally and `git commit --amend --signoff --no-edit && git push origin --force`. 🙄
=> Update "next section" link for added disconnected content.

OWNERS
Removing myself as a core maintainer. It was great working with you all!
=> Remove youreddy from core maintainers list

302-signing-workflows.md
=> CNAB Security 302: Signing workflows

Dockerfile.ajv, Makefile, brigade.js, scripts/validate-url.sh, scripts/validate.sh
* adds schema URL validation now that the files are served via https://cnab.io
Ref https://github.com/cnabio/cnab.io/pull/20
=> ci(*): add schema URL validation

101-bundle-json.md, 103-bundle-runtime.md, examples/101.01-bundle.json, examples/101.02-bundle.json, examples/101.03-bundle.json, examples/103.01-relocation-mapping.json
There were a few references to my DockerHub repo and Gabe's ACR repo. I replaced those with generic `example` repos.
=> removed unnecessary references to the original authors' registries

400-claims.md
This supersedes #295 
This PR fixes the field definitions on the claims spec to be more specific.
=> Formalize Claims fields

schema/bundle.schema.json, schema/claim.schema.json, schema/definitions.schema.json, schema/status.schema.json
* updates all `$ref`s involving the `cnab.io` domain to use `https`
Closes https://github.com/cnabio/cnab-spec/issues/284
=> ref(schema): update all cnab.io schema refs to use https

README.md
=> Add explicit links to tags and branches that contain published versions

400-claims.md, schema/claim.schema.json
This is a follow-up to https://github.com/cnabio/cnab-spec/pull/340/files#r387811084
=> Add cancelled claim status

300-CNAB-security.md
Signed-off-by: Trishank Karthik Kuppusamy <trishank.kuppusamy@datadoghq.com>
=> Fix broken link in 300

901-process.md
* Adds documentation as developed from the proposal in https://github.com/cnabio/cnab-spec/issues/351
Closes https://github.com/cnabio/cnab-spec/issues/351
=> docs(901-process.md): add Git versioning section

300-CNAB-security.md
=> Remove reference to Figure 1

000-index.md
* Adds an entry in the index to the well-known custom extensions doc
=> docs(000-index.md): add entry for well-known custom extensions

000-index.md
* Adds entry in the index for the CNAB-Dependencies spec
=> docs(000-index.md): add entry for CNAB-Dependencies

300-CNAB-security.md, 805-airgap.md, 806-security-known-implementations.md
To resolve one issue in #369 
Signed-off-by: Trishank Karthik Kuppusamy <trishank.kuppusamy@datadoghq.com>
=> Discuss airgapped environments

README.md
=> Fixed a typo in the table of contents

101-bundle-json.md, 500-CNAB-dependencies.md, examples/101.03-bundle.json, schema/dependencies.schema.json
Add sequence definition to CNAB-dependencies in order to enable ordering behavior
Closes #361
=> 500-CNAB-dependencies-sequence

400-claims.md
Version and text updates for the forthcoming proposed CNAB Claims 1.0.0 release
Ref https://github.com/cnabio/cnab-spec/issues/389
=> chore(400-claims.md): update version in anticipation of the 1.0.0 release
